// All 35 videos wired from Drive folder "video edit" (Anyone with link).
// Embed: https://drive.google.com/file/d/<id>/preview
const VIDEOS = [
  { id: "1GIgBcVAAeVQAE33DAkoOIRJ5iraB_1E4", title: "0822(1)", tag: "Reel" },
  { id: "18kK1xF7hT64k7F0gd5TWLPKQQQ_TtX4Q", title: "5", tag: "Reel" },
  { id: "13v-63Tu9HVm_dORtJN5PPe0NHBxeUZrU", title: "50sec final", tag: "Reel" },
  { id: "1embAbKycW_VT-vfSHCXRKGC_KFSsHKGr", title: "401K Contribution Ad", tag: "Ad" },
  { id: "1pUm43wwx0lBLBLjzIwdPp3ZGz50nLeGq", title: "Coca-Cola Branding", tag: "Branding" },
  { id: "1fGWh1k_ZHY1FHMPxn5hdRXzdtYJAzkcS", title: "Document l", tag: "Reel" },
  { id: "1cvlFQK1PKGGFL06g-boMP7m9MOg8d-pL", title: "Document", tag: "Reel" },
  { id: "1QK_PrEUSKrx7rR1Uk3o80bqQQy41Vy5O", title: "Example 1", tag: "Motion Graphics" },
  { id: "1uxHnYv-8U69Bp1kX0pHiXVpf-cy-Rwrd", title: "Example 2", tag: "Motion Graphics" },
  { id: "1Mb9orowPdPBIdxvdpEnxTDaA3eLvJfoh", title: "Exp 2", tag: "Reel" },
  { id: "1RnJ-7QMywZnYr3a_QF3oORc9ZptlpSzp", title: "Explainer 1", tag: "Explainer" },
  { id: "1HvlaWk3FGWopL1GKwlUnQ07VVVivEJrW", title: "Export 03", tag: "Reel" },
  { id: "1Z5RHGECUIUvj35ZmnsBEbBmERkeW5_RR", title: "Export 05", tag: "Reel" },
  { id: "1ER7w5SV9R5bSw878LPv0nApvMMJSubqY", title: "Final Video 1", tag: "Reel" },
  { id: "1H6hOn5EHShh0Qu6TIIQGRa44zsZBLYhh", title: "Forex 1", tag: "Ad" },
  { id: "1w9uSVq5oh-Oq-r9y8NYqiBzeiFTP3aZy", title: "Gozel Ora", tag: "Reel" },
  { id: "1umXSsawGdD0q95sqDKNXM8SIpOUD2EUj", title: "Guardiora", tag: "Reel" },
  { id: "1XzPwoUEj5JtVpwSlU34QM4cZ-_FeqctV", title: "Linked Comp 02_4", tag: "Motion Graphics" },
  { id: "1AIZ8f_fGdF9VfEYfiDLEL-AgyGtW4GnN", title: "Infotik Ads", tag: "Ad" },
  { id: "1WmbIGOloiO3qKvyaftvvnDsxL7uKU6ad", title: "Linked Comp 02_2", tag: "Motion Graphics" },
  { id: "1vEtxXISF8BjXnnHA2Fje-kxvOMVZkKJR", title: "QA Wolf", tag: "Ad" },
  { id: "1WS8b0k1jY3Alvnhzb_PgSomC4GnaQCnf", title: "Quadratic", tag: "Explainer" },
  { id: "1LbFx-192OoH5HmylO7gQdYmyeYfAWr3B", title: "Reel 001.1", tag: "Reel" },
  { id: "1LiZ8CnNsagxwiHsEHiCZ-L9oMqOl2iDg", title: "Reel 3 - v3", tag: "Reel" },
  { id: "1yVTzM35FJE9kjPYalfKl6GAQaBu4Swwx", title: "Sample", tag: "Reel" },
  { id: "1yG-CRhTjZYlsXWjS6uXO3BXlmMmpxtUC", title: "Sequence 01", tag: "Motion Graphics" },
  { id: "15ECYxr3iam8oXnKUEQxgT7z-Dlc3iSor", title: "Twin Mind Final", tag: "Reel" },
  { id: "1Lduaz9C7ZcYTuuTHA39onSsYQl7LRTei", title: "Version Enhanced", tag: "Reel" },
  { id: "1acvLPJaqp5WAEZluL6nfPTrhlJAE67cc", title: "VID 20260831", tag: "Reel" },
  { id: "1X5Sl8dIyDEWECECQaeYT5PgVQEE-CztB", title: "Video 7", tag: "Reel" },
  { id: "1P1zKlrcfLPLU6kIb74dmZfZcKmcqc4cO", title: "Video-64826", tag: "Reel" },
  { id: "1YTTYknkowto8D9X_USfpd5gS04knId4x", title: "Video-65945", tag: "Reel" },
  { id: "1YT3jsp5WSzyc86Jq81e9iXW87LGPBtd3", title: "Video-85028", tag: "Reel" },
  { id: "18xJtwYxFMG044It3mRynTEZGITk1R-CN", title: "Wizzzuuu", tag: "Reel" },
  { id: "1uShrZvloqXnfzR86Fu18nA_xTsi5D-A9", title: "Xyz", tag: "Reel" },
];
