// All 35 videos wired from Drive folder "video edit" (Anyone with link).
// Embed: https://drive.google.com/file/d/<id>/preview
const VIDEOS = [
  { id: "1GIgBcVAAeVQAE33DAkoOIRJ5iraB_1E4", title: "Reel 01", tag: "Reel" },
  { id: "18kK1xF7hT64k7F0gd5TWLPKQQQ_TtX4Q", title: "Reel 02", tag: "Reel" },
  { id: "13v-63Tu9HVm_dORtJN5PPe0NHBxeUZrU", title: "Reel 03", tag: "Reel" },
  { id: "1embAbKycW_VT-vfSHCXRKGC_KFSsHKGr", title: "Finance Ad — 401K", tag: "Ad" },
  { id: "1pUm43wwx0lBLBLjzIwdPp3ZGz50nLeGq", title: "Coca-Cola Brand Film", tag: "Branding" },
  { id: "1fGWh1k_ZHY1FHMPxn5hdRXzdtYJAzkcS", title: "Reel 04", tag: "Reel" },
  { id: "1cvlFQK1PKGGFL06g-boMP7m9MOg8d-pL", title: "Reel 05", tag: "Reel" },
  { id: "1QK_PrEUSKrx7rR1Uk3o80bqQQy41Vy5O", title: "Motion Design 01", tag: "Motion Graphics" },
  { id: "1uxHnYv-8U69Bp1kX0pHiXVpf-cy-Rwrd", title: "Motion Design 02", tag: "Motion Graphics" },
  { id: "1Mb9orowPdPBIdxvdpEnxTDaA3eLvJfoh", title: "Reel 06", tag: "Reel" },
  { id: "1RnJ-7QMywZnYr3a_QF3oORc9ZptlpSzp", title: "Explainer Video 01", tag: "Explainer" },
  { id: "1HvlaWk3FGWopL1GKwlUnQ07VVVivEJrW", title: "Reel 07", tag: "Reel" },
  { id: "1Z5RHGECUIUvj35ZmnsBEbBmERkeW5_RR", title: "Reel 08", tag: "Reel" },
  { id: "1ER7w5SV9R5bSw878LPv0nApvMMJSubqY", title: "Reel 09", tag: "Reel" },
  { id: "1H6hOn5EHShh0Qu6TIIQGRa44zsZBLYhh", title: "Forex Promo Ad", tag: "Ad" },
  { id: "1w9uSVq5oh-Oq-r9y8NYqiBzeiFTP3aZy", title: "Reel 10", tag: "Reel" },
  { id: "1umXSsawGdD0q95sqDKNXM8SIpOUD2EUj", title: "Reel 11", tag: "Reel" },
  { id: "1XzPwoUEj5JtVpwSlU34QM4cZ-_FeqctV", title: "Motion Comp 01", tag: "Motion Graphics" },
  { id: "1AIZ8f_fGdF9VfEYfiDLEL-AgyGtW4GnN", title: "Infotik Brand Ad", tag: "Ad" },
  { id: "1WmbIGOloiO3qKvyaftvvnDsxL7uKU6ad", title: "Motion Comp 02", tag: "Motion Graphics" },
  { id: "1vEtxXISF8BjXnnHA2Fje-kxvOMVZkKJR", title: "QA Wolf Product Ad", tag: "Ad" },
  { id: "1WS8b0k1jY3Alvnhzb_PgSomC4GnaQCnf", title: "Quadratic Explainer", tag: "Explainer" },
  { id: "1LbFx-192OoH5HmylO7gQdYmyeYfAWr3B", title: "Reel 12", tag: "Reel" },
  { id: "1LiZ8CnNsagxwiHsEHiCZ-L9oMqOl2iDg", title: "Reel 13", tag: "Reel" },
  { id: "1yVTzM35FJE9kjPYalfKl6GAQaBu4Swwx", title: "Reel 14", tag: "Reel" },
  { id: "1yG-CRhTjZYlsXWjS6uXO3BXlmMmpxtUC", title: "Title Sequence 01", tag: "Motion Graphics" },
  { id: "15ECYxr3iam8oXnKUEQxgT7z-Dlc3iSor", title: "Reel 15", tag: "Reel" },
  { id: "1Lduaz9C7ZcYTuuTHA39onSsYQl7LRTei", title: "Reel 16", tag: "Reel" },
  { id: "1acvLPJaqp5WAEZluL6nfPTrhlJAE67cc", title: "Reel 17", tag: "Reel" },
  { id: "1X5Sl8dIyDEWECECQaeYT5PgVQEE-CztB", title: "Reel 18", tag: "Reel" },
  { id: "1P1zKlrcfLPLU6kIb74dmZfZcKmcqc4cO", title: "Reel 19", tag: "Reel" },
  { id: "1YTTYknkowto8D9X_USfpd5gS04knId4x", title: "Reel 20", tag: "Reel" },
  { id: "1YT3jsp5WSzyc86Jq81e9iXW87LGPBtd3", title: "Reel 21", tag: "Reel" },
  { id: "18xJtwYxFMG044It3mRynTEZGITk1R-CN", title: "Reel 22", tag: "Reel" },
  { id: "1uShrZvloqXnfzR86Fu18nA_xTsi5D-A9", title: "Reel 23", tag: "Reel" },
];
