// Paste your Drive file IDs below. Each entry: { id: "YOUR_FILE_ID", title: "...", tag: "..." }
// Get ID from share link: https://drive.google.com/file/d/<THIS_PART>/preview
const VIDEOS = [
  { id: "", title: "Video5", tag: "Reel" },
  { id: "", title: "Video50sec final", tag: "Reel" },
  { id: "", title: "Video0822", tag: "Reel" },
  { id: "", title: "401K Contribution Ad", tag: "Ad" },
  { id: "", title: "Coca-Cola Branding", tag: "Branding" },
  { id: "", title: "Document l", tag: "Reel" },
  { id: "", title: "Document", tag: "Reel" },
  { id: "", title: "Example 1", tag: "Motion Graphics" },
  { id: "", title: "Example 2", tag: "Motion Graphics" },
  { id: "", title: "Exp 2", tag: "Reel" },
  { id: "", title: "Explainer 1", tag: "Explainer" },
  { id: "", title: "Export 03", tag: "Reel" },
  { id: "", title: "Export 05", tag: "Reel" },
  { id: "", title: "Final Video 1", tag: "Reel" },
  { id: "", title: "Forex 1", tag: "Ad" },
  { id: "", title: "Gozel Ora", tag: "Reel" },
  { id: "", title: "Guardiora", tag: "Reel" },
  { id: "", title: "Linked Comp 02_4", tag: "Motion Graphics" },
  { id: "", title: "Infotik Ads", tag: "Ad" },
  { id: "", title: "Linked Comp 02_2", tag: "Motion Graphics" },
  { id: "", title: "QA Wolf", tag: "Ad" },
  { id: "", title: "Quadratic", tag: "Explainer" },
  { id: "", title: "Reel 001.1", tag: "Reel" },
  { id: "", title: "Reel 3 - v3", tag: "Reel" },
  { id: "", title: "Sample", tag: "Reel" },
  { id: "", title: "Sequence 01", tag: "Motion Graphics" },
  { id: "", title: "Twin Mind Final", tag: "Reel" },
  { id: "", title: "Version Enhanced", tag: "Reel" },
  { id: "", title: "VID 20260831", tag: "Reel" },
  { id: "", title: "Video 7", tag: "Reel" },
  { id: "", title: "Video-64826", tag: "Reel" },
  { id: "", title: "Video-65945", tag: "Reel" },
  { id: "", title: "Video-85028", tag: "Reel" },
  { id: "", title: "Wizzzuuu", tag: "Reel" },
  { id: "", title: "Xyz", tag: "Reel" },
];
